/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeTools */

#ifndef _Included_NativeTools
#define _Included_NativeTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeTools
 * Method:    calHist
 * Signature: (IIIII[I[F[I[F[F[F[F)V
 */
JNIEXPORT void JNICALL Java_NativeTools_calHist
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jintArray, jfloatArray, jintArray, jfloatArray, jfloatArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
